// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}

type UserRegisterCheckReq struct {
	Email         string `json:"email"`
	MobileNo      string `json:"mobile_no"`
	MobileCountry string `json:"mobile_country"`
	RegisterType  string `json:"register_type"`
}

type UserRegisterCheckResp struct {
	Status string `json:"status"`
}

type UserRegisterReq struct {
	UserName      string `json:"user_name"`
	Email         string `json:"email"`
	MobileNo      string `json:"mobile_no"`
	MobileCountry string `json:"mobile_country"`
	Password      string `json:"password"`
	SmsCode       string `json:"sms_code"`
	EmailCode     string `json:"email_code"`
	OauthToken    string `json:"oauth_token"`
	OauthProvider string `json:"oauth_provider"`
	RegisterType  string `json:"register_type"`
}

type UserRegisterResp struct {
	UserName string `json:"user_name"`
	UserID   string `json:"user_id"`
	Token    string `json:"token"`
}

type UserLoginReq struct {
	UserName      string `json:"user_name"`
	UserNameSn    string `json:"user_name_sn"`
	Email         string `json:"email"`
	MobileNo      string `json:"mobile_no"`
	MobileCountry string `json:"mobile_country"`
	Password      string `json:"password"`
	SmsCode       string `json:"sms_code"`
	MfaCode       string `json:"mfa_code"`
	LoginType     string `json:"login_type"`
}

type UserLoginResp struct {
	UserName string `json:"user_name"`
	UserID   string `json:"user_id"`
	Token    string `json:"token"`
}

type SendEmailCodeReq struct {
	Code  string `json:"code"`
	Email string `json:"email"`
}

type SendSmsCodeReq struct {
	Code          string `json:"code"`
	MobileNo      string `json:"mobile_no"`
	MobileCountry string `json:"mobile_country"`
}

type SendCodeResp struct {
	Message string `json:"message"`
	Status  string `json:"status"`
}
