version: '3'

################################################################################################
#
# ref:
#   - https://taskfile.dev/#/usage
#
################################################################################################


#
# sub namespace: https://taskfile.dev/#/usage?id=including-other-taskfiles
#
includes:
  os:
    taskfile: ./script/Taskfile_{{OS}}.yml
    dir: ./script

  base:
    taskfile: ./script/Taskfile_base.yml
    dir: .

  go:
    taskfile: ./script/Taskfile_base_go.yml
    dir: .

  local:
    taskfile: ./deploy/local
    dir: ./deploy/local

  #
  # 待测试的服务根目录: 不支持从 .env 读取
  #
  app:demo:
    taskfile: ./app/basic/demo
    dir: ./app/basic/demo

  app:queue:
    taskfile: ./app/basic/queue
    dir: ./app/basic/queue

################################################################################################

#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

#
# global env: https://taskfile.dev/#/usage?id=environment-variables
#
env:
  ENV1: testing-env

# env file:
dotenv:
  - .env

################################################################################################

#
# task groups: https://taskfile.dev/#/usage?id=task-directory
#
tasks:
  default:
    cmds:
      - task: init
      - task: run

  install:
    cmds:
      - task: os:install
      - task: go:install
      - task: go:install-go-zero
      - task: go:install-proto

  init:
    cmds:
      - task: os:init
      - task: go:init

  tidy:
    cmds:
      - task: go:tidy

  update:
    cmds:
      - export GOPROXY=https://goproxy.cn; go get -u -v github.com/better-go/pkg@v0.1.17
      - echo $GOPROXY
#      - export GOPROXY=https://goproxy.cn; go get -u -v github.com/tal-tech/go-zero@v1.2.0
#      - export GOPROXY=https://goproxy.cn; go get -u -v github.com/tal-tech/go-zero@v1.1.10

  version:
    cmds:
      - task: os:version
      - task: go:version

  ################################################################################################

  infra:
    cmds:
      - task: local:init

  infra:stop:
    cmds:
      - task: local:clean

  ################################################################################################

  run:
    cmds:
      - task: app:demo:run  # set app first

  api:test:
    cmds:
      - task: app:demo:api:test

  ################################################################################################

  new-app-basic:
    cmds:
      - task: go:app-gen-basic

  new-app-biz:
    cmds:
      - task: go:app-gen-biz

  new-service-api:
    cmds:
      - goctl api new ./tmp/demo

  new-service-rpc:
    cmds:
      - goctl rpc new ./tmp/demo

  new-service-proto:
    cmds:
      - goctl rpc template -o ./tmp/demo.proto

  ################################################################################################

  push:
    cmds:
      - task: base:push
