version: '3'

################################################################################################
#
# ref:
#   - https://taskfile.dev/#/usage
#
################################################################################################

#
# sub namespace: https://taskfile.dev/#/usage?id=including-other-taskfiles
#
includes:
  platform:
    taskfile: ./script/Taskfile_{{OS}}.yml
    dir: ./script

  base:
    taskfile: ./script/Taskfile_base.yml
    dir: .

  go:
    taskfile: ./script/Taskfile_base_go.yml
    dir: .


################################################################################################

#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

#
# global env: https://taskfile.dev/#/usage?id=environment-variables
#
env:
  ENV1: testing-env

# env file:
dotenv:
  - .env

################################################################################################

#
# task groups: https://taskfile.dev/#/usage?id=task-directory
#
tasks:
  default:
    cmds:
      - task: init
      - task: run

  install:
    cmds:
      - task: platform:install
      - task: go:install
      - task: go:install-go-zero
      - task: go:install-proto

  init:
    cmds:
      - task: platform:init
      - task: go:init

  tidy:
    cmds:
      - task: go:tidy

  update:
    cmds:
      - export GOPROXY=https://goproxy.cn; go get -u -v github.com/better-go/pkg@v0.1.17
      - echo $GOPROXY
#      - export GOPROXY=https://goproxy.cn; go get -u -v github.com/tal-tech/go-zero@v1.2.0
#      - export GOPROXY=https://goproxy.cn; go get -u -v github.com/tal-tech/go-zero@v1.1.10

  version:
    cmds:
      - task: platform:version
      - task: go:version


  ################################################################################################

  new-app-basic:
    cmds:
      - task: go:app-gen-basic

  new-app-biz:
    cmds:
      - task: go:app-gen-biz

  new-service-api:
    cmds:
      - goctl api new ./tmp/demo

  new-service-rpc:
    cmds:
      - goctl rpc new ./tmp/demo

  new-service-proto:
    cmds:
      - goctl rpc template -o ./tmp/demo.proto

  run:
    cmds:
      - go run tmp/demo/demo.go -f tmp/demo/etc/demo-api.yaml

  curl-api:
    cmds:
      - curl -i http://localhost:8888/from/you



  ################################################################################################

  push:
    cmds:
      - task: base:push
