##########################################################################################
#                              consul service:
# ref:
#   - https://github.com/bitnami/containers
#     - https://github.com/bitnami/containers/blob/main/bitnami/consul/docker-compose.yml
#   - 本地浏览器访问:
#     - http://localhost:8500/ui/
#   - FAQ:
#     - docker 启动失败报 volume 无操作权限, 可以删除 volume, 重新启动
#
##########################################################################################

version: '3'

services:
  consul:
    image: consul:latest
    container_name: consul
    #    platform: linux/amd64
    #    restart: always
    #    environment:
    #      CONSUL_BIND_INTERFACE: eth0
    volumes:
      - consul_data:/consul/data/
    networks:
      - consul_net
    ports:
      - "8500:8500"
    command: [ agent,-server,-ui,-client=0.0.0.0,-bootstrap-expect=1, -node=node1 ]


##########################################################################################
#                                 自定义依赖:
##########################################################################################

# 自定义网络:
networks:
  consul_net:
    driver: bridge

# 自定义数据卷:
volumes:
  consul_data:
    driver: local
