version: '3'

################################################################################################
#
# ref:
#   - https://taskfile.dev/#/styleguide
#     - https://taskfile.dev/#/styleguide?id=use-the-correct-order-of-keywords
#     - https://taskfile.dev/#/styleguide?id=use-colon-for-task-namespacing
#   - yml format: https://juejin.cn/post/6844903972688363534
#
################################################################################################

vars:
  COMPOSE_FILE:

################################################################################################

tasks:
  default:
    cmds:
      - task: init

  echo:
    cmds:
      - echo "hello deploy/local"


  ################################################################################################

  init:
    cmds:
      - task: up:mysql
      - task: up:redis
      - task: up:rabbitmq
      #      - task: up:etcd
      - task: up:etcd2    # check here!

  clean:
    cmds:
      - task: down:mysql
      - task: down:rabbitmq
      - task: down:etcd

  ################################################################################################

  up:redis:
    cmds:
      - task: docker:up
        vars:
          { COMPOSE_FILE: infra-cache-redis.yml }

  up:rabbitmq:
    cmds:
      - task: docker:up
        vars:
          { COMPOSE_FILE: infra-mq-rabbitmq.yml }

  up:mysql:
    cmds:
      - task: docker:up
        vars:
          { COMPOSE_FILE: infra-db-mysql.yml }

  # ETCDCTL_API =2 或者 3, 切换 API 版本
  up:etcd2:
    cmds:
      - |
        docker run -d -it --rm \
        --name etcd_test \
        -e ETCDCTL_API=3 \
        -p 2379:2379 \
        -p 2380:2380 \
        quay.io/coreos/etcd:v3.3.9 \
        etcd \
        --advertise-client-urls http://0.0.0.0:2379 \
        --listen-client-urls http://0.0.0.0:2379

  up:etcd:
    cmds:
      - task: docker:up
        vars:
          { COMPOSE_FILE: infra-kv-etcd.yml }

  up:consul:
    cmds:
      - echo "run consul"
      - docker-compose -f infra-kv-consul.yml up -d
      - docker-compose -f infra-kv-consul.yml logs  # -f


  down:consul:
    cmds:
      - echo "stop consul"
      - docker-compose -f infra-kv-consul.yml down
      - docker ps


  ################################################################################################

  exec:etcd:
    cmds:
      - task: docker:exec
        vars:
          { CONTANIER_NAME: etcd_test }

  ################################################################################################

  test:etcd:v2:
    cmds:
      - curl http://127.0.0.1:2379/v2/keys/ | python -m json.tool

  # https://github.com/etcd-io/etcd/issues/6904
  # ETCDCTL_API=3 ./etcdctl get / --prefix --keys-only
  test:etcd:v3:
    cmds:
      - etcdctl get "" --prefix --keys-only | sed '/^\s*$/d'

  ################################################################################################

  down:redis:
    cmds:
      - task: docker:down
        vars:
          { COMPOSE_FILE: infra-cache-redis.yml }

  down:rabbitmq:
    cmds:
      - task: docker:down
        vars:
          { COMPOSE_FILE: infra-mq-rabbitmq.yml }

  down:mysql:
    cmds:
      - task: docker:down
        vars:
          { COMPOSE_FILE: infra-db-mysql.yml }

  down:etcd:
    cmds:
      - task: docker:down
        vars:
          { COMPOSE_FILE: infra-kv-etcd.yml }

  ################################################################################################

  docker:up:
    cmds:
      - docker-compose -f {{.COMPOSE_FILE}} up -d
      - docker-compose -f {{.COMPOSE_FILE}} ps

  docker:down:
    cmds:
      - docker-compose -f {{.COMPOSE_FILE}} down --remove-orphans
      - docker-compose -f {{.COMPOSE_FILE}} ps

  docker:log:
    cmds:
      - docker-compose -f {{.COMPOSE_FILE}} logs -f

  docker:exec:
    cmds:
      - docker exec -it {{.CONTANIER_NAME}} sh

  ################################################################################################

  # 提取本机 IP:
  #	- https://cloud.tencent.com/developer/article/1015510
  ip:get:mac:
    cmds:
      - ifconfig | grep inet | grep -v inet6 | grep -v 127 | cut -d ' ' -f2

  ip:get:linux:
    cmds:
      - ip a | grep inet | grep -v inet6 | grep -v 127 | sed 's/^[ \t]*//g' | cut -d ' ' -f2






