// Code generated by goctl. DO NOT EDIT.
package service

import (
	"net/http"

	"github.com/tal-tech/go-zero/rest"

	svc "mall/app/basic/demo/internal/domain/demo"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/from/:name",
				Handler: DemoHandler(serverCtx),
			},
		},
	)
}
