version: '3'

################################################################################################
#
# ref:
#   - https://taskfile.dev/#/styleguide
#     - https://taskfile.dev/#/styleguide?id=use-the-correct-order-of-keywords
#     - https://taskfile.dev/#/styleguide?id=use-colon-for-task-namespacing
#   - yml format: https://juejin.cn/post/6844903972688363534
#
################################################################################################


tasks:
  default:
    cmds:
      - task: run

  tidy:
    cmds:
      - go mod tidy -v

  run:
    cmds:
      - air # 自动watch 代码变更, 热加载:

  run:debug:
    cmds:
      - go run cmd/main.go -f configs/configs.yaml

  api:test:
    cmds:
      - curl -i http://localhost:8888/from/you


  proto:gen:
    cmds:
      - |
        find ./ -iname "*.proto" -exec \
          protoc --proto_path=. \
            --proto_path=../../../pkg/x \
            --go_out=paths=source_relative:. \
            --go-http_out=paths=source_relative:. \
            --go-grpc_out=paths=source_relative:. \
            --openapi_out==paths=source_relative:. \
            {} \;
      - go generate ./...
